from .cpc import CPCWidget
from .psm import PSMWidget
from .co2 import CO2Widget
from .electrometer import ElectrometerWidget
from .rhtp import RHTPWidget
from .ediluter import eDiluterWidget
from .afm import AFMWidget
from .tsi_cpc import TSIWidget
from .example import ExampleDeviceWidget
